version: '3'
services:
 jekyll:
  build: .
  container_name: jekyll
  image: doctorhalsey/universe-theme
  command: jekyll serve --watch --host "0.0.0.0" # --config _config.yml,_config.dev.yml
  ports:
  - "4000:4000"
  volumes:
  - .:/app